# For detailed sponsorship information, see SPONSORS.md

github: R3alM0m1X82
custom: 
  - https://paypal.me/mohammedbellala
  # More info: https://github.com/R3alM0m1X82/SpecterPortal/blob/main/SPONSORS.md
